
export const DIAGNOSIS_CATEGORIES = [
  {
    name: "اضطرابات المزاج",
    diagnoses: [
      "Major Depressive Disorder",
      "Persistent Depressive Disorder (Dysthymia)",
      "Bipolar I Disorder",
      "Bipolar II Disorder",
      "Cyclothymic Disorder",
      "Premenstrual Dysphoric Disorder",
      "Disruptive Mood Dysregulation Disorder",
      "Substance/Medication-Induced Depressive Disorder",
      "Depressive Disorder Due to Another Medical Condition",
    ],
  },
  {
    name: "اضطرابات القلق",
    diagnoses: [
      "Generalized Anxiety Disorder",
      "Panic Disorder",
      "Social Anxiety Disorder",
      "Specific Phobia",
      "Agoraphobia",
      "Separation Anxiety Disorder",
      "Selective Mutism",
      "Substance/Medication-Induced Anxiety Disorder",
      "Anxiety Disorder Due to Another Medical Condition",
    ],
  },
  {
    name: "اضطرابات الوسواس والاضطرابات ذات الصلة",
    diagnoses: [
      "Obsessive-Compulsive Disorder",
      "Body Dysmorphic Disorder",
      "Hoarding Disorder",
      "Trichotillomania",
      "Excoriation Disorder",
      "Substance/Medication-Induced OCD",
    ],
  },
  {
    name: "اضطرابات الصدمة والكرب",
    diagnoses: [
      "Post-Traumatic Stress Disorder",
      "Acute Stress Disorder",
      "Adjustment Disorders",
      "Reactive Attachment Disorder",
      "Disinhibited Social Engagement Disorder",
      "Prolonged Grief Disorder",
    ],
  },
  {
    name: "اضطرابات ذهانية",
    diagnoses: [
      "Schizophrenia",
      "Brief Psychotic Disorder",
      "Schizophreniform Disorder",
      "Schizoaffective Disorder",
      "Delusional Disorder",
      "Substance/Medication-Induced Psychotic Disorder",
      "Psychotic Disorder Due to Another Medical Condition",
      "Catatonia",
    ],
  },
  {
    name: "اضطرابات الأكل",
    diagnoses: [
      "Anorexia Nervosa",
      "Bulimia Nervosa",
      "Binge Eating Disorder",
      "Avoidant/Restrictive Food Intake Disorder",
      "Pica",
      "Rumination Disorder",
      "Night Eating Syndrome",
    ],
  },
  {
    name: "اضطرابات النوم واليقظة",
    diagnoses: [
      "Insomnia Disorder",
      "Hypersomnolence Disorder",
      "Narcolepsy",
      "Nightmare Disorder",
      "REM Sleep Behavior Disorder",
      "Restless Legs Syndrome",
      "Circadian Rhythm Sleep-Wake Disorders",
      "Sleep Apnea",
    ],
  },
  {
    name: "اضطرابات الشخصية",
    diagnoses: [
      "Borderline Personality Disorder",
      "Antisocial Personality Disorder",
      "Narcissistic Personality Disorder",
      "Avoidant Personality Disorder",
      "Obsessive-Compulsive Personality Disorder",
      "Paranoid Personality Disorder",
      "Schizoid Personality Disorder",
      "Schizotypal Personality Disorder",
      "Histrionic Personality Disorder",
      "Dependent Personality Disorder",
    ],
  },
  {
    name: "اضطرابات النمو العصبي",
    diagnoses: [
      "Attention-Deficit/Hyperactivity Disorder",
      "Autism Spectrum Disorder",
      "Intellectual Disability",
      "Tourette's Disorder",
      "Persistent (Chronic) Motor or Vocal Tic Disorder",
      "Specific Learning Disorder",
      "Developmental Coordination Disorder",
    ],
  },
];
