
export const SYMPTOM_CATEGORIES = [
  {
    name: "الأعراض المزاجية (Mood Symptoms)",
    symptoms: [
      "Depressed Mood",
      "Anhedonia",
      "Euphoria",
      "Irritability",
      "Mood Lability",
      "Dysphoria",
      "Alexithymia",
    ],
  },
  {
    name: "الأعراض الذهانية (Psychotic Symptoms)",
    symptoms: [
      "Hallucinations",
      "Delusions",
      "Paranoia",
      "Thought Insertion",
      "Thought Broadcasting",
      "Thought Withdrawal",
      "Ideas of Reference",
      "Disorganized Thinking",
    ],
  },
  {
    name: "أعراض القلق (Anxiety Symptoms)",
    symptoms: [
      "Generalized Anxiety",
      "Panic Attacks",
      "Phobias",
      "Social Anxiety",
      "Agoraphobia",
      "Anticipatory Anxiety",
      "Free-Floating Anxiety",
    ],
  },
  {
    name: "الأعراض المعرفية (Cognitive Symptoms)",
    symptoms: [
      "Memory Impairment",
      "Concentration Deficit",
      "Executive Dysfunction",
      "Disorientation",
      "Confusion",
      "Cognitive Rigidity",
      "Poor Judgment",
    ],
  },
  {
    name: "الأعراض السلوكية (Behavioral Symptoms)",
    symptoms: [
      "Psychomotor Agitation",
      "Psychomotor Retardation",
      "Catatonia",
      "Compulsions",
      "Impulsivity",
      "Self-Harm Behavior",
      "Aggression",
      "Social Withdrawal",
    ],
  },
  {
    name: "أعراض النوم (Sleep Symptoms)",
    symptoms: [
      "Insomnia",
      "Hypersomnia",
      "Nightmares",
      "Sleep Terror",
      "Circadian Rhythm Disturbance",
    ],
  },
  {
    name: "الأعراض الجسدية (Somatic Symptoms)",
    symptoms: [
      "Fatigue",
      "Appetite Changes",
      "Weight Changes",
      "Psychomotor Symptoms",
      "Somatization",
      "Conversion Symptoms",
    ],
  },
  {
    name: "أعراض الوعي والإدراك (Consciousness & Perception)",
    symptoms: [
      "Depersonalization",
      "Derealization",
      "Dissociation",
      "Flashbacks",
      "Hypervigilance",
    ],
  },
  {
    name: "أعراض إضافية مهمة",
    symptoms: [
      "Suicidal Ideation",
      "Homicidal Ideation",
      "Obsessions",
      "Rumination",
      "Racing Thoughts",
      "Flight of Ideas",
      "Circumstantial Thinking",
      "Tangential Thinking",
      "Loose Associations",
      "Neologisms",
      "Echolalia",
      "Mutism",
      "Alogia",
      "Avolition",
      "Apathy",
      "Emotional Blunting",
      "Labile Affect",
    ],
  },
  {
    name: "أعراض الإدمان والاعتمادية (Addiction & Dependence)",
    symptoms: [
      "Craving",
      "Tolerance",
      "Withdrawal Symptoms",
      "Loss of Control",
      "Preoccupation",
    ],
  },
  {
    name: "أعراض الأكل (Eating Symptoms)",
    symptoms: [
      "Binge Eating",
      "Purging Behavior",
      "Food Restriction",
      "Body Image Distortion",
      "Fear of Weight Gain",
    ],
  },
  {
    name: "أعراض الصدمة (Trauma Symptoms)",
    symptoms: [
      "Re-experiencing",
      "Avoidance",
      "Emotional Numbing",
      "Exaggerated Startle Response",
      "Survivor Guilt",
    ],
  },
  {
    name: "أعراض الشخصية (Personality Symptoms)",
    symptoms: [
      "Identity Disturbance",
      "Chronic Emptiness",
      "Fear of Abandonment",
      "Splitting",
      "Idealization/Devaluation",
    ],
  },
  {
    name: "أعراض جنسية (Sexual Symptoms)",
    symptoms: [
      "Decreased Libido",
      "Hypersexuality",
      "Sexual Dysfunction",
      "Gender Dysphoria",
    ],
  },
  {
    name: "أعراض النمو العصبي (Neurodevelopmental)",
    symptoms: [
      "Hyperactivity",
      "Inattention",
      "Stereotypies",
      "Echopraxia",
      "Tics",
    ],
  },
  {
    name: "أعراض إضافية متخصصة",
    symptoms: [
      "Confabulation",
      "Perseveration",
      "Ambivalence",
      "Anergy",
      "Bradyphrenia",
      "Pressured Speech",
      "Poverty of Speech",
      "Blocking",
      "Derailment",
      "Clanging",
      "Word Salad",
      "Waxy Flexibility",
      "Negativism",
      "Posturing",
      "Stupor",
      "Akathisia",
      "Dystonia",
      "Tardive Dyskinesia",
      "Formication",
      "Cenesthopathy",
      "Autoscopy",
    ],
  },
];
